name: Deploy PostgreSQL to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          #client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          #auth-type: OIDC

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=DB-Server init

      - name: Terraform Plan
        run: terraform -chdir=DB-Server plan -var="admin_password=${{ secrets.PSQL_ADMIN_PASSWORD }}"

      - name: Terraform Apply
        run: terraform -chdir=DB-Server apply -auto-approve -var="admin_password=${{ secrets.PSQL_ADMIN_PASSWORD }}"
